// Docs: https://www.instantdb.com/docs/modeling-data

import { i } from "@instantdb/react";

const _schema = i.schema({
  entities: {
    $files: i.entity({
      path: i.string().unique().indexed(),
      url: i.string(),
    }),
    $users: i.entity({
      email: i.string().unique().indexed().optional(),
      imageURL: i.string().optional(),
      type: i.string().optional(),
    }),
    todos: i.entity({
      text: i.string(),
      done: i.boolean(),
      createdAt: i.number(),
    }),
    // Lottery Results Entities
    ultra_lotto_6_58_results: i.entity({
      draw_date: i.string(),
      draw_number: i.string().optional(),
      number_1: i.number(),
      number_2: i.number(),
      number_3: i.number(),
      number_4: i.number(),
      number_5: i.number(),
      number_6: i.number(),
      jackpot: i.number().optional(),
      winners: i.number().optional(),
      created_at: i.string(),
    }),
    grand_lotto_6_55_results: i.entity({
      draw_date: i.string(),
      draw_number: i.string().optional(),
      number_1: i.number(),
      number_2: i.number(),
      number_3: i.number(),
      number_4: i.number(),
      number_5: i.number(),
      number_6: i.number(),
      jackpot: i.number().optional(),
      winners: i.number().optional(),
      created_at: i.string(),
    }),
    super_lotto_6_49_results: i.entity({
      draw_date: i.string(),
      draw_number: i.string().optional(),
      number_1: i.number(),
      number_2: i.number(),
      number_3: i.number(),
      number_4: i.number(),
      number_5: i.number(),
      number_6: i.number(),
      jackpot: i.number().optional(),
      winners: i.number().optional(),
      created_at: i.string(),
    }),
    mega_lotto_6_45_results: i.entity({
      draw_date: i.string(),
      draw_number: i.string().optional(),
      number_1: i.number(),
      number_2: i.number(),
      number_3: i.number(),
      number_4: i.number(),
      number_5: i.number(),
      number_6: i.number(),
      jackpot: i.number().optional(),
      winners: i.number().optional(),
      created_at: i.string(),
    }),
    lotto_6_42_results: i.entity({
      draw_date: i.string(),
      draw_number: i.string().optional(),
      number_1: i.number(),
      number_2: i.number(),
      number_3: i.number(),
      number_4: i.number(),
      number_5: i.number(),
      number_6: i.number(),
      jackpot: i.number().optional(),
      winners: i.number().optional(),
      created_at: i.string(),
    }),
    // Lottery Predictions Entities
    ultra_lotto_6_58_predictions: i.entity({
      target_draw_date: i.string(),
      model_type: i.string(),
      predicted_number_1: i.number(),
      predicted_number_2: i.number(),
      predicted_number_3: i.number(),
      predicted_number_4: i.number(),
      predicted_number_5: i.number(),
      predicted_number_6: i.number(),
      previous_prediction_1: i.string().optional(),
      previous_prediction_2: i.string().optional(),
      previous_prediction_3: i.string().optional(),
      previous_prediction_4: i.string().optional(),
      previous_prediction_5: i.string().optional(),
      result_id: i.string().optional(),
      created_at: i.string(),
    }),
    grand_lotto_6_55_predictions: i.entity({
      target_draw_date: i.string(),
      model_type: i.string(),
      predicted_number_1: i.number(),
      predicted_number_2: i.number(),
      predicted_number_3: i.number(),
      predicted_number_4: i.number(),
      predicted_number_5: i.number(),
      predicted_number_6: i.number(),
      previous_prediction_1: i.string().optional(),
      previous_prediction_2: i.string().optional(),
      previous_prediction_3: i.string().optional(),
      previous_prediction_4: i.string().optional(),
      previous_prediction_5: i.string().optional(),
      result_id: i.string().optional(),
      created_at: i.string(),
    }),
    super_lotto_6_49_predictions: i.entity({
      target_draw_date: i.string(),
      model_type: i.string(),
      predicted_number_1: i.number(),
      predicted_number_2: i.number(),
      predicted_number_3: i.number(),
      predicted_number_4: i.number(),
      predicted_number_5: i.number(),
      predicted_number_6: i.number(),
      previous_prediction_1: i.string().optional(),
      previous_prediction_2: i.string().optional(),
      previous_prediction_3: i.string().optional(),
      previous_prediction_4: i.string().optional(),
      previous_prediction_5: i.string().optional(),
      result_id: i.string().optional(),
      created_at: i.string(),
    }),
    mega_lotto_6_45_predictions: i.entity({
      target_draw_date: i.string(),
      model_type: i.string(),
      predicted_number_1: i.number(),
      predicted_number_2: i.number(),
      predicted_number_3: i.number(),
      predicted_number_4: i.number(),
      predicted_number_5: i.number(),
      predicted_number_6: i.number(),
      previous_prediction_1: i.string().optional(),
      previous_prediction_2: i.string().optional(),
      previous_prediction_3: i.string().optional(),
      previous_prediction_4: i.string().optional(),
      previous_prediction_5: i.string().optional(),
      result_id: i.string().optional(),
      created_at: i.string(),
    }),
    lotto_6_42_predictions: i.entity({
      target_draw_date: i.string(),
      model_type: i.string(),
      predicted_number_1: i.number(),
      predicted_number_2: i.number(),
      predicted_number_3: i.number(),
      predicted_number_4: i.number(),
      predicted_number_5: i.number(),
      predicted_number_6: i.number(),
      previous_prediction_1: i.string().optional(),
      previous_prediction_2: i.string().optional(),
      previous_prediction_3: i.string().optional(),
      previous_prediction_4: i.string().optional(),
      previous_prediction_5: i.string().optional(),
      result_id: i.string().optional(),
      created_at: i.string(),
    }),
  },
  links: {
    $usersLinkedPrimaryUser: {
      forward: {
        on: "$users",
        has: "one",
        label: "linkedPrimaryUser",
        onDelete: "cascade",
      },
      reverse: {
        on: "$users",
        has: "many",
        label: "linkedGuestUsers",
      },
    },
  },
  rooms: {
    todos: {
      presence: i.entity({}),
    },
  },
});

// This helps Typescript display nicer intellisense
type _AppSchema = typeof _schema;
interface AppSchema extends _AppSchema {}
const schema: AppSchema = _schema;

export type { AppSchema };
export default schema;
